# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.url }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gaphor
logo: /images/gaphor.svg
tagline: Gaphor, the UML/SysML modeling tool
description: >-
    Gaphor is a UML and SysML modeling application written in Python. It is
    designed to be easy to use, while still being powerful. Gaphor implements a
    fully-compliant UML 2 data model, so it is much more than a picture drawing
    tool. You can use Gaphor to quickly visualize different aspects of a system
    as well as create complete, highly complex models.
url: https://gaphor.org
favicon: /images/gaphor-24x24.png
gaphor_version: 2.3.0
google_tracking_id: UA-9578559-2

menu:
    - label: About
      url: "/#about"
    - label: Download
      url: "/download.html"
    - label: Tutorials
      url: "/tutorials.html"
    - label: Blog
      url: "/blog.html"
    - label: Get in touch
      url: "/discuss.html"
    - label: Contribute
      url: "/contribute.html"
    - label: "<i class='fab fa-github' style='font-size: 168%' title='GitHub repository'></i>"
      url: "https://github.com/gaphor/gaphor"

colors:
    - "#50bc7c"
    - "#E0C512"
    - "#6664bd"
    - "#E0C512"
    - "#6664bd"
    - "#50bc7c"

umlcolors:
    - "#971232"
    - "#c7c000"
    - "#54006c"

defaults:
    - scope:
          path: ""
      values:
          layout: "default"
    - scope:
          path: "_drafts*"
      values:
          layout: "post"
    - scope:
          path: "_posts*"
      values:
          layout: "post"
    - scope:
          path: "_tutorials*"
      values:
          layout: "article"

collections:
    usps:
    platforms:
    tutorials:
        output: true

sass:
    style: compressed

highlighter: rouge

plugins:
    # - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-redirect-from

exclude:
    - Gemfile
    - Gemfile.lock
    - README.md
    - LICENSE.txt
    - images/*.xcf
